# Generated by Django 2.2.5 on 2019-09-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.TextField(max_length=25)),
                ('pass_usuario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('id_categoria', models.TextField()),
                ('nombre_producto', models.TextField(max_length=50)),
                ('precio_producto', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
